; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FF43BA53-C19E-4278-AD71-60162436216E}
AppName=Clipboard Bridge
AppVersion=1.0.0
;AppVerName=Clipboard Bridge 1.0.0
DefaultDirName={autopf}\Clipboard Bridge
UninstallDisplayIcon={app}\Clipboard Bridge.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Richiede privilegi di amministratore coerenti con l'installazione globale
PrivilegesRequired=admin
OutputBaseFilename=mysetup
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[CustomMessages]
; Stringhe personalizzate per supportare il multilingua nell'opzione di avvio
english.StartupDescription=Launch Clipboard Bridge on Windows startup (As Admin)
italian.StartupDescription=Avvia Clipboard Bridge all'avvio di Windows (Come Amministratore)

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "windowsstartup"; Description: "{cm:StartupDescription}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\Clipboard Bridge.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Clipboard Bridge"; Filename: "{app}\Clipboard Bridge.exe"
Name: "{autodesktop}\Clipboard Bridge"; Filename: "{app}\Clipboard Bridge.exe"; Tasks: desktopicon

[Run]
; Crea l'attività pianificata per l'avvio come Admin (eseguita solo se la Task 'windowsstartup' è selezionata)
Filename: "schtasks"; Parameters: "/Create /TN ""ClipboardBridgeStartup"" /TR ""'{app}\Clipboard Bridge.exe'"" /SC ONLOGON /RL HIGHEST /F"; Flags: runhidden; Tasks: windowsstartup

; Avvia il programma al termine dell'installazione
Filename: "{app}\Clipboard Bridge.exe"; Description: "{cm:LaunchProgram,Clipboard Bridge}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Eliminazione sicura dell'attività pianificata con RunOnceId per rimuovere il Warning
Filename: "schtasks"; Parameters: "/Delete /TN ""ClipboardBridgeStartup"" /F"; Flags: runhidden; RunOnceId: "DeleteClipboardBridgeStartupTask"
