; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#ifndef MyAppVersion
  #define MyAppVersion "2.0.0"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FF43BA53-C19E-4278-AD71-60162436216E}
AppName=Clipboard Bridge
AppVersion={#MyAppVersion}
AppVerName=Clipboard Bridge {#MyAppVersion}
AppPublisher=Clipboard Bridge
AppPublisherURL=https://github.com/mattbox03/Clipboard-Bridge
AppSupportURL=https://github.com/mattbox03/Clipboard-Bridge/issues
AppUpdatesURL=https://github.com/mattbox03/Clipboard-Bridge/releases/latest
DefaultDirName={localappdata}\Programs\Clipboard Bridge
UninstallDisplayIcon={app}\Clipboard Bridge.exe
; The bundled executable is built for x64 Windows and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
DisableProgramGroupPage=yes
; Per-user installation avoids UAC and never writes application data in Program Files.
PrivilegesRequired=lowest
OutputBaseFilename=Clipboard.Bridge_windows_client_and_server_setup_x64_V{#MyAppVersion}
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[CustomMessages]
english.StartupDescription=Launch Clipboard Bridge when you sign in to Windows
italian.StartupDescription=Avvia Clipboard Bridge all'accesso a Windows

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "windowsstartup"; Description: "{cm:StartupDescription}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\Clipboard Bridge.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Clipboard Bridge"; Filename: "{app}\Clipboard Bridge.exe"
Name: "{autodesktop}\Clipboard Bridge"; Filename: "{app}\Clipboard Bridge.exe"; Tasks: desktopicon
Name: "{userstartup}\Clipboard Bridge"; Filename: "{app}\Clipboard Bridge.exe"; Tasks: windowsstartup

[Run]
; Launch the application when an interactive installation finishes.
Filename: "{app}\Clipboard Bridge.exe"; Description: "{cm:LaunchProgram,Clipboard Bridge}"; Flags: nowait postinstall skipifsilent
