services:
  clipboard-bridge:
    build: .
    container_name: clipboard-bridge
    ports:
      - "5088:5088"
    volumes:
      # directory of hystory
      - ./data:/data
    environment:
      - CLIPBOARD_MAX_HISTORY=200
      # uncomment to protect your server with token:
      # - CLIPBOARD_TOKEN=change_this_token
    restart: unless-stopped
